# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc5e82356b2a61e998499ee85727bd644ca198b1f35ec63e3be6a08bbfd5d6e218e90073927e19a40a01ad5264f10e9a5d9140fb701caf7b4ba63a38cfcaff72

test:
  secret_key_base: 6beebbb782f1e2944cdd3dad4c61f97ff6a523b485a7bbfb258d948275d12e3c03eea3d236af85704bbac1f064cb7604be21dd5e9ee4a693d89a4e07d7d5d289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
